In [179]:
import pandas as pd 
from sklearn.preprocessing  import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,recall_score,precision_score,f1_score
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import joblib

In [63]:
# pca=PCA(n_components=None)
# x_pca=pca.fit_transform(X_train)
# xt_pca=pca.transform(X_test)

In [64]:
# explained_variance=pca.explained_variance_ratio_
# formatted_array = ["{:.3f}".format(value) for value in explained_variance]
# formatted_array

['0.279', '0.182', '0.154', '0.147', '0.114', '0.097', '0.027']

In [68]:
# lda=LinearDiscriminantAnalysis(n_components=7)
# x_trainlda=lda.fit_transform(X_train,Y_train)
# x_testlda=lda.transform(X_test)

In [69]:
# ldamodel=DecisionTreeClassifier()
# ldamodel.fit(x_trainlda,Y_train)

DecisionTreeClassifier()

In [70]:
# ldapred=ldamodel.predict(x_testlda)

In [71]:
# accuracy_score(ldapred,Y_test)

0.9590909090909091

In [2]:
data=pd.read_csv('Crop_recommendation.csv')

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   N            2200 non-null   int64  
 1   P            2200 non-null   int64  
 2   K            2200 non-null   int64  
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object 
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB


In [14]:
data

N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

<h1>N - ratio of Nitrogen content in soil</br>
P - ratio of Phosphorous content in soil</br>
K - ratio of Potassium content in soil</br>
temperature - temperature in degree Celsius</br>
humidity - relative humidity in %</br>
ph - ph value of the soil</br>
rainfall - rainfall in mm </h1>

In [155]:
X=data.iloc[:,0:7].values
Y=data.iloc[:,7]

In [156]:
len(Y.unique())

22

In [22]:
labelencoder=LabelEncoder()
Y=labelencoder.fit_transform(Y)

In [25]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [28]:
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [32]:
treemodel=DecisionTreeClassifier()
treemodel.fit(X_train,Y_train)

DecisionTreeClassifier()

In [176]:
pred=treemodel.predict(X_test)


In [180]:
accuracy_score(pred,Y_test)
recall_score(pred,Y_test ,average=None, zero_division=1)
# precision_score(pred,Y_test ,average=None, zero_division=1)
f1_score(pred,Y_test, average='micro')


0.975

In [59]:
labelencoder.inverse_transform([Y_test[1]])

array(['mungbean'], dtype=object)

In [58]:
labelencoder.inverse_transform(treemodel.predict([X_test[1]]))

array(['mungbean'], dtype=object)

In [40]:
for ok in confusion_matrix(pred,Y_test):
    print(ok)

[18  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
[ 0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
[ 0  0 22  0  0  0  0  0  0  0  1  0  0  1  0  0  0  0  0  0  0  0]
[ 0  0  0 24  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
[ 0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
[ 0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
[ 0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
[ 0  0  0  0  0  0  0 13  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
[ 0  0  0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  2  0]
[ 0  0  0  0  0  0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0]
[ 0  0  1  0  0  0  0  0  0  0 23  0  0  1  0  0  0  0  0  0  0  0]
[ 0  0  1  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0]
[ 0  0  0  0  0  0  0  0  0  0  0  0 16  0  0  0  0  0  0  0  0  0]
[ 0  0  0  0  0  0  0  0  0  0  1  0  0 15  0  0  0  0  0  0  0  0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 16  0

In [77]:
joblib.dump(labelencoder, 'labelencoder.pkl')

['labelencoder.pkl']

In [78]:
joblib.dump(sc, 'standarscaler.pkl')

['standarscaler.pkl']

In [75]:
joblib.dump(treemodel, 'decision_tree_model.pkl')

['decision_tree_model.pkl']

<h1> Decision Tree gave a very good result  that might not be beatten but lets try a deep learning model</h1>

In [106]:
import torch 
import pytorch_lightning as PL
import torch.nn as nn 
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset,DataLoader
from torchmetrics.functional import accuracy

In [165]:
class DeepModel(PL.LightningModule):
    def __init__(self):
        super().__init__()
        self.hidden1=nn.Linear(7,10)
        self.act1=nn.ReLU()
        self.hidden2=nn.Linear(10,10)
        self.act2=nn.ReLU()
        self.out=nn.Linear(10,22)
#         self.actout=F.softmax()
    def forward(self,x):
        x = x.to(self.hidden1.weight.dtype)
        x=self.hidden1(x)
        x=self.act1(x)
        x=self.hidden2(x)
        x=self.act2(x)
        return F.softmax(self.out(x))
    def training_step(self, batch, batch_nb):
        x, y = batch
        logits = self(x)
        loss = F.cross_entropy(logits, y)
        pred = logits.argmax(dim=1)
        acc = accuracy(pred, y,task='multiclass', num_classes=22)
        return loss 
    def configure_optimizers(self):
        return optim.Adam(self.parameters(), lr=0.01)

In [166]:
deepmodel=DeepModel()

In [167]:
class Predata(Dataset):
    def __init__(self,X,Y):
        super().__init__()
        self.X=torch.tensor(X)
        self.Y=torch.LongTensor(Y)
    def __len__(self):
        return len(self.X)
    def __getitem__(self,index):
        x=self.X[index]
        y=self.Y[index]
        return x,y

In [168]:
trainingset=Predata(X_train,Y_train)
testinngset=Predata(X_test,Y_test)

In [169]:
train_loader=DataLoader(trainingset,10)

In [170]:
trainer = PL.Trainer(max_epochs=50, accelerator='cpu')

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs


In [171]:
trainer.fit(deepmodel, train_loader)


  | Name    | Type   | Params
-----------------------------------
0 | hidden1 | Linear | 80    
1 | act1    | ReLU   | 0     
2 | hidden2 | Linear | 110   
3 | act2    | ReLU   | 0     
4 | out     | Linear | 242   
-----------------------------------
432       Trainable params
0         Non-trainable params
432       Total params
0.002     Total estimated model params size (MB)


Training: 0it [00:00, ?it/s]

C:\Users\hp\AppData\Local\Temp\ipykernel_42104\3905046773.py:16: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.softmax(self.out(x))
`Trainer.fit` stopped: `max_epochs=50` reached.


In [161]:
testx=[]
testy=[]
for ok in testinngset:
    ok=list(ok)
    testx.append(ok[0])
    testy.append(ok[1])

In [172]:
total=len(testx)
correct=0
for myx,myy in zip(testx,testy):
    out=deepmodel(myx)
    pred=out.argmax()
    if pred==myy:
        correct+=1

C:\Users\hp\AppData\Local\Temp\ipykernel_42104\3905046773.py:16: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.softmax(self.out(x))


In [173]:
correct/total

0.9068181818181819

In [174]:
# torch.save(deepmodel, 'torch_model.pt')

In [186]:
testx[1],testy[1]

(tensor([-0.3320, -0.5259, -0.5381,  0.4715,  0.5985,  0.1128, -1.2281],
        dtype=torch.float64),
 tensor(14))

In [187]:
deepmodel(testx[1]),deepmodel(testx[1]).argmax()

C:\Users\hp\AppData\Local\Temp\ipykernel_42104\3905046773.py:16: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.softmax(self.out(x))


(tensor([4.8577e-18, 3.2707e-31, 3.2088e-21, 8.7944e-40, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 4.4128e-19, 2.3375e-40, 0.0000e+00, 1.0922e-14, 0.0000e+00,
         2.7929e-40, 8.6242e-22, 1.0000e+00, 2.4338e-32, 3.5859e-23, 3.2342e-26,
         1.1491e-43, 1.9343e-24, 0.0000e+00, 0.0000e+00],
        grad_fn=<SoftmaxBackward0>),
 tensor(14))